### ISSUE TITLE
react-hook-form

### ISSUE THREAD

**Issue by smooJitter** [davideddr/react-native-hook-form-builder#1]
Does this use react-hook-form under the hood.  I see references to react-hook-form on the readme page but not in the source code?

**Comment by davideddr** [comment]
Hi @smooJitter! You can find react-hook-form in the Form component under the lib/components [folder](https://github.com/davideddr/react-native-hook-form-builder/blob/master/lib/components/Form.js).

**Comment by smooJitter** [comment]
Thanks!  for the work you put into this.   Solid and clean coding.  I do have a few issues with the lottie dependency considering it is only used for a checkbox.

**Comment by davideddr** [comment]
Thank you! You are right, in the new version i can try to remove this dependency and use the icons instead.

**Comment by smooJitter** [comment]
Yes!  Installing the lottie-react-native is a bit tricky on iOS (creating swift views). It took a few hours for me to rescue my project from this tricky process.  In the end, I had to remove the checkbox for now.

**Comment by davideddr** [comment]
In version 0.4.1 I remove Lottie from dependencies.
