### ISSUE TITLE
Remove the usage of react-native-nested-scroll-view

### ISSUE THREAD

**Issue by Derewith** [davideddr/react-native-hook-form-builder#6]
Today i've came across the upgrading of an app to React Native 0.64 and react-native-nested-scroll-view is not anymore updated.

I've done a patch that remove the usage of it (NestedScrollView) and use the ScrollView default React Native component, i think it's way better.

**Comment by davideddr** [comment]
Thank you @Derewith for the tip! In the 0.11.4 version i removed the react-native-nested-scroll-view in favor of the ScrollView component
